apiVersion: v1
kind: Pod
metadata:
  name: dice-app
  labels:
    app: dice
spec:
  restartPolicy: Always
  containers:
  - name: dice-container
    image: gojo2405/dice-app:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dice-service
spec:
  selector:
    app: dice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
