name: Deploy Dice App (Docker + Nginx)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop and remove old container
        run: |
          docker stop dice-app || true
          docker rm dice-app || true

      - name: Remove old image (optional)
        run: |
          docker rmi dice-app || true

      - name: Build Docker image
        run: |
          docker build -t dice-app .

      - name: Run container
        run: |
          docker run -d -p 80:80 --name dice-app dice-app
