name: Deploy Dice App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop and remove old container
        run: |
          docker rm -f dice-app || true

      - name: Build Docker image
        run: docker build -t dice-app .

      - name: Run container
        run: |
          docker run -d -p 80:80 --name dice-app dice-app
